### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by vickysharma0812** [urbanjost/M_ncurses#1]
Dear @urbanjost

Kindly change the name of the following file

`https://github.com/urbanjost/M_ncurses/blob/master/docs/ncurses_from_Fortran.html`

to 

`https://github.com/urbanjost/M_ncurses/blob/master/docs/index.html`

so that

`https://urbanjost.github.io/M_ncurses/`

works 😄 

Regards
Vikas

**Comment by urbanjost** [comment]
I renamed it and it appears to work.  I have several projects without an index.html file that I assumed were being accessed by a name such as https://github.com/urbanjost/M_ncurses instead of https://urbanjost.github.io/M_ncurses. I may have several other files to rename or create!   Thanks.  [M_ncurses](https://urbanjost.github.io/M_ncurses) should work directly now.
